/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author alexj
 */
public class VentanaPaint extends javax.swing.JFrame {
    
    BufferedImage buffer = null;
    BufferedImage buffer2 = null;
    //monto un objeto de tipo circulo llamado auxiliar.
    Ellipse2D.Double auxiliar;
    
    /**
     * Creates new form VentanaPaint
     */
    public VentanaPaint() {
        initComponents();
        inicializaBuffers();
    }

    private void inicializaBuffers(){
        //creo una imagen del mismo ancho y alto que el lienzo llamado buffer.
        buffer = (BufferedImage) lienzo.createImage(lienzo.getWidth(), lienzo.getHeight());
        //creo una imagen modificable
        Graphics2D g2 = buffer.createGraphics();
        //dibujamos un rectangulo blanco del tamaño del lienzo
        g2.setColor(Color.white); //le doy color blanco
        g2.fillRect(0, 0, lienzo.getWidth(), lienzo.getHeight()); //y el tamaño de la imagen del alto y ancho de lienzo
        
        
        
        //inicializo el 2º buffer
        //creo una imagen del mismo ancho y alto que el lienzo llamado buffer.
        buffer2 = (BufferedImage) lienzo.createImage(lienzo.getWidth(), lienzo.getHeight());
        //creo una imagen modificable, sin el Graphics2D porq lo tengo declarado arriba.
        g2 = buffer2.createGraphics();
        //dibujamos un rectangulo blanco del tamaño del lienzo
        g2.setColor(Color.white); //le doy color blanco
        g2.fillRect(0, 0, buffer2.getWidth(), buffer2.getHeight()); //y el tamaño de la imagen del alto y ancho de lienzo
    }
    
    @Override //modifico el metodo padre paint()
    public void paint(Graphics g){
        super.paint(g); //coge el parametro de la clase padre.
        //apuntamos al lienzo
        Graphics2D g2 = (Graphics2D) lienzo.getGraphics(); //casteo para convertir el Grphics en Graphics2D
        g2.drawImage(buffer, 0, 0, null); //dibujamosm el buffer en la posicion 0, 0 y es null (para que llene el resto)
                                          //ponemos el null porq el metodo drawImage, necesita 4 parametros, el null no lo usa.
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzoMouseDragged(evt);
            }
        });
        lienzo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lienzoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lienzoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMousePressed
        //creo el objeto auxiliar, ancho y alto del evento del raton (movimiento de este) y su ancho y alto del dibujo
        auxiliar = new Ellipse2D.Double(evt.getX(), evt.getY(), 10, 10);
        //para dibujarlo usamos graphics y como necesitamos un metodo de graphics2D, lo cateamos y...
        Graphics2D g2 = (Graphics2D) buffer.getGraphics();
        //.... usamos el metodo que queremos para rellenar auxiliar con color
        g2.fill(auxiliar);
        //le decimos que repinte en el buffer el objeto
        repaint(0, 0, 1, 1);
    }//GEN-LAST:event_lienzoMousePressed
//metodo para que dibuje un tamaño determinado cuando el raton se desplace cuando esta pulsado.
    private void lienzoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseDragged
        Graphics2D g2 = (Graphics2D) buffer.getGraphics(); //casteo para convertir el Grphics en Graphics2D
        //sobrescribimos el buffer para que lo dibujado no se borre
        g2.drawImage(buffer2, 0, 0, null);
        
       //creamos una variable int llamada radio, restamos la posicion X del circulo y le restamos la posX del evento de raton
       //como dara negativo, lo metemos dentro de un Math.abs (absoluto) y nos lo devolvera positivo, el (int) es para
       //decirle que sera de tipo int.
        int radio = Math.abs((int)auxiliar.x - evt.getX());
        //le cambiamos el alto y el ancho al circulo
        auxiliar.width = radio;
        auxiliar.height = radio;
        g2.setColor(Color.black);
        g2.fill(auxiliar);
        //apuntamos al lienzo
        g2 = (Graphics2D) buffer.getGraphics();
        g2.drawImage(buffer, 0, 0, null);
        repaint(0, 0, 1, 1);
    }//GEN-LAST:event_lienzoMouseDragged

    private void lienzoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseReleased
        //esto lo usamos para guardar lo que se haya dibujado en el buffer1,
        //para que no se borre cuando el raton se suelte.
        Graphics2D g2 = (Graphics2D) buffer2.getGraphics();
        
        g2.fill(auxiliar);
        
        
    }//GEN-LAST:event_lienzoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel lienzo;
    // End of variables declaration//GEN-END:variables
}
